version: '3.8'

services:
# Servicio database
  db:
    build:
      context: ./database
    container_name: simi_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pharmacy_erp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - simi-net
    
# Servicio web front y backend
  web:
    build:
      context: ./backend
    container_name: simi_web
    restart: always
    ports:
      - "80:80"
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_NAME=pharmacy_erp
    networks:
      - simi-net

volumes:
  pgdata: # Volumen para la database

networks:
  simi-net:
    driver: bridge # red interna de docker